stages:
  - smoke
  - test
  - package


smoke-backend:
  stage: smoke
  image: node:20-alpine
  script:
    - "cd backend"
    - "npm i"
    - "timeout 30s node app.js || [[ $? -eq 143 ]]"

test-backend:
  stage: test
  image: node:20-alpine
  script:
    - cd backend
    - npm i
    - npm test

package-project:
  stage: package
  image: alpine:latest
  script:
    - apk add zip
    - zip -r project.zip .
  artifacts:
    paths:
      - project.zip
  only:
    - main