@host = http://85.215.71.124

###

GET {{host}}/homepage HTTP/1.1
Content-Type: application/json

{
    "userID": "661d5aeb7caebb258991f758",
    "usedIDs": [
        {
            "type": "activity",
            "id": "666b427d862f539d60f295a7"
        },
        {
            "type": "event",
            "id": "666ab2f5fdddd3a93373a2a2"
        },
        {
            "type": "game",
            "id": "6671f7f1e377d21fdd9e296c"
        }
    ]
}

###


PUT {{host}}/homepage HTTP/1.1
Content-Type: application/json

{
    "userID": "663bd3b7969fc6302facf1ee",
    "usedIDs": null
}

###

GET {{host}}/homepage/661d5aeb7caebb258991f758