@host = http://localhost:3000

###

GET {{host}}/user/gamsa HTTP/1.1

###

GET {{host}}/user/events/661d07706671060e01a4fd3d HTTP/1.1

###

POST {{host}}/user/cah/Cryptoooo HTTP/1.1

###

POST {{host}}/user/changePassword/ HTTP/1.1
Content-Type: application/json

{
    "userID": "661d07706671060e01a4fd3d",
    "newPassword": "JoelStinkt!100"
}

###

POST {{host}}/user/changeEmail/ HTTP/1.1
Content-Type: application/json

{
    "userID": "661d07706671060e01a4fd3d",
    "newEmail": "l.bauscher@gmx.de"
}

###

PUT {{host}}/user/addEvent HTTP/1.1
Content-Type: application/json

{
    "userID": "661d07706671060e01a4fd3d",
    "eventID": "666ab2f5fdddd3a93373e2r2"
}

###

POST {{host}}/user/changeUsername HTTP/1.1
Content-Type: application/json

{
    "userID": "661d07706671060e01a4fd3d",
    "newUsername": "TheLars"
}

###

PUT {{host}}/user/changeLastName HTTP/1.1
Content-Type: application/json

{
    "userID": "661d07706671060e01a4fd3d",
    "newName": "Gerigkiiiii"
}

###

DELETE {{host}}/user/661d07706671060e01a4fd3d/JoelStinkt*100 HTTP/1.1

###

DELETE {{host}}/user/661d09ba6671060e01a4fd3e/Alladin!101 HTTP/1.1


