@host = http://85.215.71.124

###

POST {{host}}/activities/postActivity HTTP/1.1
Content-Type: application/json

{
    "caption": "BeispielKommentar",
    "userID": "661d09ba6671060e01a4fd3e",
    "gameID": "666399b2836465f324792e54"
}

###

GET {{host}}/activities/661d09ba6671060e01a4fd3e

###

GET {{host}}/activities/getActivitiesFromUser/661d07706671060e01a4fd3d

###

PUT {{host}}/activities/addReaction HTTP/1.1
Content-Type: application/json

{
    "userID": "661d09ba6671060e01a4fd3e",
    "activityID": "6666311b8663e5335a54e9b4",
    "reactionType": "beer"
}

###

DELETE {{host}}/activities/661d5aeb7caebb258991f758/666b427d862f539d60f295a7/love