@host = http://localhost:3000

###

POST {{host}}/events HTTP/1.1
Content-Type: application/json

{
    "date": "01.10",
    "name": "Unithekle",
    "time": "ab 20 Uhr",
    "header": "Vaihingen • 7 Apr 2024",
    "desc": "Imagine a drinking night with Jordine...",
    "tags": [
        "community", "120 sips"
    ]
}

###

POST {{host}}/events HTTP/1.1
Content-Type: application/json

{
    "date": "07.04",
    "name": "AprilApril",
    "time": "ab 19 Uhr",
    "header": "Vaihingen • 7 Apr 2024",
    "desc": "Imagine a night full of unforgettable pranks and laughter, where every moment holds a new surprise - that's our April Fool's party!",
    "tags": ["community", "100 sips"]
}

###

POST {{host}}/events HTTP/1.1
Content-Type: application/json

{
    "date": "25.05",
    "name": "Bartour",
    "time": "ab 19 Uhr",
    "header": "Vaihingen • 7 Apr 2024",
    "desc": "Imagine a night full of unforgettable pranks and laughter, where every moment holds a new surprise - that's our April Fool's party!",
    "tags": ["community", "100 sips"]
}

###

POST {{host}}/events HTTP/1.1
Content-Type: application/json

{
    "date": "13.06",
    "name": "Straussi II",
    "time": "ab 19 Uhr",
    "header": "Vaihingen • 7 Apr 2024",
    "desc": "Imagine a night full of unforgettable pranks and laughter, where every moment holds a new surprise - that's our April Fool's party!",
    "tags": ["community", "100 sips"]
}

###

POST {{host}}/events HTTP/1.1
Content-Type: application/json

{
    "date": "06.07",
    "name": "MediaNight",
    "time": "ab 17 Uhr",
    "header": "Vaihingen • 7 Apr 2024",
    "desc": "Imagine a night full of unforgettable pranks and laughter, where every moment holds a new surprise - that's our April Fool's party!",
    "tags": ["community", "100 sips"]
}

###

GET {{host}}/events HTTP/1.1

###