@host = http://85.215.71.124:3000

###

POST {{host}}/friends HTTP/1.1
Content-Type: application/json

{
    "fromSipsterID": "gamsa",
    "toSipsterID": "jeel"
}

###

DELETE {{host}}/friends/gamsa/jeel?status=true HTTP/1.1

###

DELETE {{host}}/friends/gamsa/jeel?status=false HTTP/1.1

###

DELETE {{host}}/friends/gamsa/jeel?remove=true

###

GET {{host}}/friends/gamsa

###