@host = http://localhost:3000

###

POST {{host}}/friends HTTP/1.1
Content-Type: application/json

{
    "fromSipsterID": "gamsa",
    "toSipsterID": "jeel"
}

###

POST {{host}}/friends HTTP/1.1
Content-Type: application/json

{
    "fromSipsterID": "gamsa",
    "toSipsterID": "Crypto"
}

###

POST {{host}}/friends HTTP/1.1
Content-Type: application/json

{
    "fromSipsterID": "jeel",
    "toSipsterID": "gamsa"
}

###
DELETE {{host}}/friends/gamsa/jeel?status=true HTTP/1.1 

###

DELETE {{host}}/friends/gamsa/jeel?status=false HTTP/1.1

###

DELETE {{host}}/friends/friendTest/Sipster?remove=true

###

GET {{host}}/friends/Sipster

###

GET {{host}}/friends/gamsa/m

###

GET {{host}}/friends/invitations/gamsa