@host = http://85.215.71.124


###

GET {{host}}/login/jeel/larsstinkt_*100 HTTP/1.1


###

GET {{host}}/login/Cryptocryxx/psw HTTP/1.1


###

GET {{host}}/login/gamsa/JoelStinkt*100 HTTP/1.1


###

GET {{host}}/login/Crypto/crYpT123!!! HTTP/1.1

###

GET {{host}}/login/juuliaeb/juuls123!E HTTP/1.1