@host = http://localhost:3000

###

POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
    "username": "gamsa",
    "password": "lolichbinLars!12",
    "email": "larsstinkt@web.de",
    "firstName": "Lars",
    "lastName": "Gerigk",
    "friends": "null"
}

###

POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
    "username": "jöl",
    "password": "lolichbinJoel1!",
    "email": "js486@hdm-stuttgart.de",
    "firstName": "Joel",
    "lastName": "Starkov",
    "friends": "null"
}

###

POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
    "username": "Crypto",
    "password": "crYpT123!!!",
    "email": "lb486@hdm-stuttgart.de",
    "firstName": "Lars",
    "lastName": "Bauscher",
    "friends": null
}

###

POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
    "username": "lolol",
    "password": "1nMMsjf!!2!",
    "email": "abcde12345",
    "firstName": "Hänger",
    "lastName": "123",
    "friends": "null"
}

###

POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
    "username": "lolol",
    "password": "123456789",
    "email": "jeol@gmail.com",
    "firstName": "Hänger",
    "lastName": "123",
    "friends": "null"
}

###

DELETE {{host}}/register/gamsa/JoelStinkt*100 HTTP/1.1

###