@host = http://localhost:3000

###

POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
    "username": "gamsa",
    "password": "lolichbinLars!12",
    "email": "larsstinkt@web.de",
    "firstName": "Lars",
    "lastName": "Gerigk",
    "friends": "null"
}

###

POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
    "username": "jöl",
    "password": "lolichbinJoel1!",
    "email": "js486@hdm-stuttgart.de",
    "firstName": "Joel",
    "lastName": "Starkov",
    "friends": "null"
}

###

POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
    "username": "Maike",
    "password": "Sipster!24",
    "email": "mk486@hdm-stuttgart.de",
    "firstName": "Maike",
    "lastName": "König",
    "friends": null
}

###

POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
    "username": "lolol",
    "password": "1nMMsjf!!2!",
    "email": "abcde12345",
    "firstName": "Hänger",
    "lastName": "123",
    "friends": "null"
}

###

POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
    "username": "lolol",
    "password": "123456789",
    "email": "jeol@gmail.com",
    "firstName": "Hänger",
    "lastName": "123",
    "friends": "null"
}

###

DELETE {{host}}/register/Crypto/crYpT123!!! HTTP/1.1

###