@host = http://localhost:3000

###

GET {{host}}/user/Lars HTTP/1.1

###

GET {{host}}/user/Crypto/events HTTP/1.1

###

POST {{host}}/user/cah/Cryptoooo HTTP/1.1

###

POST {{host}}/user/changePassword/Cryptocryxx/JoelStinkt!100 HTTP/1.1

###

POST {{host}}/user/addEvent HTTP/1.1
Content-Type: application/json

{
    "username": "Cryptoooo",
    "eventID": "6615c7d7b30f73c8ba10bead"
}

###

POST {{host}}/user/changeUsername HTTP/1.1
Content-Type: application/json

{
    "username": "Cryptocryxx",
    "newUsername": "cryp"
}

###

DELETE {{host}}/user/661d09ba6671060e01a4fd3e/Alladin!101 HTTP/1.1


