@host = http://localhost:3000

###

GET {{host}}/user/Lars HTTP/1.1

###

GET {{host}}/user/Crypto/events HTTP/1.1

###

POST {{host}}/user/Crypto/Cryptoooo HTTP/1.1

###

POST {{host}}/user/changePassword/Cryptocryxx/JoelStinkt!100 HTTP/1.1

###

POST {{host}}/user/addEvent HTTP/1.1
Content-Type: application/json

{
    "username": "Cryptoooo",
    "eventID": "6615c7d7b30f73c8ba10bead"
}