export const events = [
    { date: "27.03", name: "Bartour", time: "ab 19 Uhr", header: "Vaihingen • 27 Mar 2024", desc: "Immerse yourself in a night full of discoveries and unforgettable moments on our legendary bar tour, where every sip and every laugh writes a new story.", tags: ["1st semester", "150 sips"] },
    { date: "07.04", name: "AprilApril", time: "ab 19 Uhr", header: "Vaihingen • 7 Apr 2024", desc: "Imagine a night full of unforgettable pranks and laughter, where every moment holds a new surprise - that's our April Fool's party!", tags: ["community", "100 sips"] },
    { date: "25.05", name: "Bartour", time: "ab 19 Uhr", header: "Vaihingen • 7 Apr 2024", desc: "Imagine a night full of unforgettable pranks and laughter, where every moment holds a new surprise - that's our April Fool's party!", tags: ["community", "100 sips"] },
    { date: "13.06", name: "Straussi II", time: "ab 19 Uhr", header: "Vaihingen • 7 Apr 2024", desc: "Imagine a night full of unforgettable pranks and laughter, where every moment holds a new surprise - that's our April Fool's party!", tags: ["community", "100 sips"] },
    { date: "06.07", name: "MediaNight", time: "ab 17 Uhr", header: "Vaihingen • 7 Apr 2024", desc: "Imagine a night full of unforgettable pranks and laughter, where every moment holds a new surprise - that's our April Fool's party!", tags: ["community", "100 sips"] },
    { date: "27.03", name: "Bartour", time: "ab 19 Uhr", header: "Vaihingen • 7 Apr 2024", desc: "Imagine a night full of unforgettable pranks and laughter, where every moment holds a new surprise - that's our April Fool's party!", tags: ["community", "100 sips"] },
    { date: "07.04", name: "AprilApril", time: "ab 19 Uhr", header: "Vaihingen • 7 Apr 2024", desc: "Imagine a night full of unforgettable pranks and laughter, where every moment holds a new surprise - that's our April Fool's party!", tags: ["community", "100 sips"] },
    { date: "25.05", name: "Bartour", time: "ab 19 Uhr", header: "Vaihingen • 7 Apr 2024", desc: "Imagine a night full of unforgettable pranks and laughter, where every moment holds a new surprise - that's our April Fool's party!", tags: ["community", "100 sips"] },
    { date: "13.06", name: "Straussi II", time: "ab 19 Uhr", header: "Vaihingen • 7 Apr 2024", desc: "Imagine a night full of unforgettable pranks and laughter, where every moment holds a new surprise - that's our April Fool's party!", tags: ["community", "100 sips"] },
    { date: "06.07", name: "MediaNight", time: "ab 17 Uhr", header: "Vaihingen • 7 Apr 2024", desc: "Imagine a night full of unforgettable pranks and laughter, where every moment holds a new surprise - that's our April Fool's party!", tags: ["community", "100 sips"] },
];